import streamlit as st
import google.generativeai as genai
import openai

# 1. Page Config & Professional Styling
st.set_page_config(page_title="GlobalScript AI Pro", page_icon="🤖")

st.markdown("""
    <style>
    #MainMenu {visibility: hidden;}
    footer {visibility: hidden;}
    header {visibility: hidden;}
    </style>
    """, unsafe_allow_html=True)

# 2. Main Branding
st.markdown("<h1 style='text-align: center;'>🤖 GlobalScript AI Pro</h1>", unsafe_allow_html=True)
st.markdown("<p style='text-align: center;'>The World's First Dual-Engine AI Script Generator</p>", unsafe_allow_html=True)

# 3. Sidebar: Select Your Engine
st.sidebar.title("⚙️ AI Engine Settings")
engine = st.sidebar.radio("Select AI Brain:", ("Google Gemini", "OpenAI ChatGPT"))

# Sidebar: Language Settings
lang_map = {
    "English": "en", "Hindi": "hi", "Punjabi": "pa", "Spanish": "es", 
    "French": "fr", "Arabic": "ar", "German": "de"
}
selected_lang = st.sidebar.selectbox("Output Language", list(lang_map.keys()))

st.sidebar.write("---")
st.sidebar.caption("System Status: Online 🟢")

# 4. Main User Interface
topic = st.text_input("Enter Video Topic:", placeholder="e.g. How to start a business in 2026")

if st.button("Generate Viral Content ✨"):
    if topic:
        with st.spinner(f"Using {engine} to write your content..."):
            # Yahan hum AI logic connect karenge jab humein Keys mil jayengi
            st.success(f"Response generated by {engine} in {selected_lang}!")
            
            # Placeholder for results
            st.subheader("📝 AI Generated Script")
            st.write(f"Wait! We need to connect the **{engine} API Key** to show the actual result here.")
    else:
        st.error("Please enter a topic.")

# 5. Hidden Dev Settings (Branding Safe)
with st.sidebar.expander("Admin Login"):
    st.text_input("API Access Key", type="password")
